name: Build Doc

on: [push]

jobs:
  test-doc:
    
    runs-on: ubuntu-latest

    steps:

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          architecture: x64
   
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          path: chiexp

      - name: Deploy
        uses: mbruno46/deploy-sphinx-doc@main
        with:
          path: doc
          doc-branch: 'gh-pages'	  
