name: Build Doc

on:
  push:
    paths:
      - 'doc/**'

jobs:
  doc:
    
    runs-on: ubuntu-latest

    steps:

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          architecture: x64
   
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup
        run: |
          python -m pip install --upgrade pip
          pip install numpy scipy

      - name: Deploy
        uses: mbruno46/deploy-sphinx-doc@main
        with:
          path: doc
          doc-branch: 'gh-pages'
          pypackages: 'nbsphinx'
