name: Test Python

on: [push]

jobs:
  test-python:
    
    runs-on: ubuntu-latest

    steps:

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          architecture: x64
   
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          path: chiexp

      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          pip install numpy scipy
          cd chiexp/examples/python
          for F in `ls *py`
          do
              python $F
          done
